### ISSUE TITLE
Uncaught Exception: TypeError: Cannot read property 'releaseInfo' of undefined at getItemVersions

### ISSUE THREAD

**Issue by Psijic** [nmrugg/UE4Launcher#10]
https://i.imgur.com/JVyZIwu.png

**Comment by stephenlake** [comment]
Can confirm, same issue here.

**Comment by LaurentOngaro** [comment]
Same issue for me

**Comment by charleshamesse** [comment]
Same here. The last console logs I get are:
```
Getting asset info...
Authorizing... 29%
```
The error is due to the fact that the launcher can't download the assetInfo json, which seems to be due to a login error. It fails in the step 3 of the login sequence, around https://github.com/nmrugg/UE4Launcher/blob/master/libs/epicApi.js#L119 
I tried a fresh install to make sure that there wasn't a conflict with old login tokens or something, but still didn't work.

**Comment by fedorenchik** [comment]
I also have the same issue.

**Comment by sradms0** [comment]
> Same here. The last console logs I get are:
> 
> ```
> Getting asset info...
> Authorizing... 29%
> ```
> 
> The error is due to the fact that the launcher can't download the assetInfo json, which seems to be due to a login error. It fails in the step 3 of the login sequence, around https://github.com/nmrugg/UE4Launcher/blob/master/libs/epicApi.js#L119
> I tried a fresh install to make sure that there wasn't a conflict with old login tokens or something, but still didn't work.

I've been messing with this, as well.
I was digging into the error occurring and there is a 404 status code coming from the apis `res.statusCode`.
I don't know if this is directly related to a login error; I could be wrong, or this is in relation to a possible login issue.

**Comment by sradms0** [comment]
I'm not sure if there was any change with Epics api super recently, but I noticed that I am able to download the 'Medieval Dungeon' pack, or re-download for that matter since I already own it.
Attempting to download any other assets do not work.
There may be something different about 'newer' assets in the marketplace, their JSON data, maybe.
Would anyone mind try to download this to see what happens for them?

**Comment by fedorenchik** [comment]
Tried to download 'Medieval Dungeon' pack. Same error occur. Have never downloaded this asset before.

![Screenshot from 2020-06-07 16-21-51](https://user-images.githubusercontent.com/391735/83963811-32189f00-a8db-11ea-83b5-73cbee1b41d7.png)

**Comment by junqingqiao** [comment]
Hi dear developers,
Thank you for your great work. It made my life a lot easier. I meet the same issue now.

**Comment by agentfeux** [comment]
Great work developer!
I have the same issue here :(

**Comment by Zartris** [comment]
This is still a problem! Any news on this?

**Comment by nmrugg** [comment]
Sorry, I haven't been able to fix this yet. Epic changed their authentication method, and I'm going to have to reverse engineer it. I've been very busy lately, but I'm working on figuring it out.

**Comment by nmrugg** [comment]
I think I have it fixed. Please update and try it now.

**Comment by agentfeux** [comment]
Its working, thanks you for fixing the issue !
